frg-fossee/eSim-Cloud

README.md
docker-compose.dev.yml
eda-frontend/.dockerignore
eda-frontend/Dockerfile

Please note this config is only for getting the full development environment running. 
for production, only the built js files will be served through the reverse proxy.

Added docker config for eda-frontend

---

README.md
docker-compose.dev.yml

HotFixes: node_modules not installed, typo in README

HotFixes: node_modules not installed, typo in README 

---

.env
Nginx/conf.d/local.conf
README.md
docker-compose.prod.yml
esim-cloud-backend/.gitignore

**NOTE: This is not the final production config**
Builds static files for django 
Migrates database models
Builds both frontends and serves them using nginx
Serves eda-frontend on localhost/eda
Serves ArduinoFrontend on localhost/arduino 
**Please ensure static images/files are present in the static or dist folder after the framework is done building, import things appropriately so it automatically places things in the dist / static folder while building**

Production config for docker-compose 

---

.github/workflows/reactTestBuild.yml
ArduinoFrontend/Dockerfile
README.md
eda-frontend/Dockerfile

Changed angular workflow to trigger only when changes are made in it's folder, but on develop branch too. 
Added Build and test config for react triggered only when changes are made in it's folder on develop and eda-frontend branches.

Build and Test Workflows 

---

esim-cloud-backend/esimCloud/urls.py
esim-cloud-backend/simulationAPI/helpers/ngspice_helper.py
esim-cloud-backend/simulationAPI/tasks.py

Fixed URL for api 
Delete files after processing 
Added logger for ngspice helper

Dev simulation api

---

eda-frontend/src/App.test.js

Fixed the test for eda-frontend react application

fixed test for react application

---

eda-frontend/src/App.test.js

Added a test which renders App 
Fixes error due to no tests found in #28 44e40e3
Fixes Issue: #24

Added dummy test 

---

.env
README.md
docker-compose.dev.yml
esim-cloud-backend/esimCloud/settings.py
esim-cloud-backend/migrations.sh
esim-cloud-backend/requirements.txt
esim-cloud-backend/simulationAPI/dbrouters.py
esim-cloud-backend/simulationAPI/models.py
first_run.dev.sh

Fixed bugs related to mongodb, Switch back to mongoDB.
The main culprit was 'djongo' library version.

Switch back to MongoDB, Added migration scripts 

---

.github/workflows/eslint.yml
JMeter/libAPI.jmx
JMeter/simulationAPI.jmx
Nginx/conf.d/local.conf
README.md
docker-compose.dev.yml
docker-compose.prod.yml
first_run.dev.sh

Eslit check bot, jmeter tests, documentation for ubuntu, nginx caching config

Eslit check bot, jmeter tests, documentation for ubuntu, nginx caching config

---

.github/workflows/prodContainers.yml

Added config to build and publish production containers to github packages.

Config to publish prod containers

---

eda-frontend/package.json
eda-frontend/src/components/SchematicEditor/ComponentSidebar.js
esim-cloud-backend/libAPI/views.py

add search functionality to search components also add different search options.

Component search

---

eda-frontend/src/components/SchematicEditor/ComponentProperties.js
eda-frontend/src/components/SchematicEditor/Helper/SvgParser.js
eda-frontend/src/components/SchematicEditor/SimulationProperties.js
eda-frontend/src/components/Shared/Graph.js
eda-frontend/src/components/Simulator/Editor.js
eda-frontend/src/components/Simulator/NetlistUpload.js
eda-frontend/src/components/Simulator/SimulationScreen.js
eda-frontend/src/components/Simulator/textToFile.js
eda-frontend/src/pages/Simulator.js

added comments
removed unwanted commented code
Fixed port position

Eda frontend add comments

---

ArduinoFrontend/src/app/Libs/Workspace.ts

https://github.com/frg-fossee/eSim-Cloud/issues/171

Handling escape and backspace buttons

---

ArduinoFrontend/src/app/Libs/General.ts
ArduinoFrontend/src/app/Libs/Point.ts
ArduinoFrontend/src/app/Libs/outputs/Display.ts
ArduinoFrontend/src/app/Libs/outputs/LCD/LCDPanel.ts
ArduinoFrontend/src/app/Libs/outputs/Led.ts

https://github.com/frg-fossee/eSim-Cloud/issues/188

Components and breadboard bugfix

---

esim-cloud-backend/requirements.txt

Duplicate of https://github.com/py-bson/bson/issues/82

Fix breaking dependencies between pymongo and bson

---

eda-frontend/src/components/SchematicEditor/Helper/ToolbarTools.js

Fixes #223 
Reducing Console Logs and Appropriate Comments added for the Functions and Conditions

Refactor Code - ToolbarTools.js 

---

ArduinoFrontend/src/app/Libs/Workspace.ts

Fixes #237 
Added a condition to check if someone is pressing backspace on input or textarea.

Pressing Backspace when on a textField won't invoke deleteComponent

---

ArduinoFrontend/package-lock.json
eda-frontend/src/App.js
eda-frontend/src/components/SchematicEditor/ComponentSidebar.js
eda-frontend/src/components/SchematicEditor/Header.js
eda-frontend/src/components/SchematicEditor/SchematicToolbar.js
eda-frontend/src/components/SchematicEditor/ToolbarExtension.js
eda-frontend/src/components/Shared/Navbar.js
eda-frontend/src/pages/Account/ChangePassword.js
eda-frontend/src/pages/Login.js
eda-frontend/src/pages/SchematiEditor.js
eda-frontend/src/pages/signUp.js
eda-frontend/src/redux/actions/accountActions.js
eda-frontend/src/redux/actions/authActions.js
eda-frontend/src/redux/actions/saveSchematicActions.js
eda-frontend/src/redux/reducers/authReducer.js
esim-cloud-backend/authAPI/urls.py
esim-cloud-backend/authAPI/views.py

- Login/logout from any tab now affects all tabs which is needed (logout deletes the token at the back-end so other tabs will be making requests with an expired one).
- if close parameter is passed in the URL of the login page the page closes after the login is done (might be helpful for Arduino sim).
- Logout from any other tab causes the tabs with editor open to present a re-login prompt. Such editor tabs will not allow any other activity until login is done or page is reloaded to remove the previous user's data.
- Clicking logout in the editor tabs now raises a confirm dialog box giving options to cancel or go through with the logout.
- Login by pressing enter key in either username or password fields.
- Added tooltip for the show password button in login form.
- Fixed the …

Improving Login system in eSim

---

eda-frontend/src/components/SchematicEditor/Helper/ToolbarTools.js

Where labels get deleted seperately before the actual component

Fixes the bug in Undo/Redo

---

ArduinoFrontend/src/app/Libs/ConvertJSONFormat.ts
ArduinoFrontend/src/app/Libs/ImageToByteArray.ts
ArduinoFrontend/src/app/Libs/SaveOffiline.ts
ArduinoFrontend/src/app/Libs/SaveOnline.ts
ArduinoFrontend/src/app/Libs/Workspace.ts
ArduinoFrontend/src/app/alert/alert-modal/alert-modal.component.css
ArduinoFrontend/src/app/alert/alert-modal/alert-modal.component.html
ArduinoFrontend/src/app/alert/alert-service/alert.service.ts
ArduinoFrontend/src/app/alert/option-modal/option-modal.component.css
ArduinoFrontend/src/app/alert/option-modal/option-modal.component.html
ArduinoFrontend/src/app/alert/option-modal/option-modal.component.ts
ArduinoFrontend/src/app/app.module.ts
ArduinoFrontend/src/app/dashboard/dashboard.component.html
ArduinoFrontend/src/app/dashboard/dashboard.component.ts

Export Circuit from Simulator with Thumbnail.
Export temporary and cloud Circuits from Dashboard in JSON file format.
Import circuits temporarily or on cloud to Dashboard from JSON file.
1. ArduinoFrontend/src/app/dashboard/dashboard.component.ts
2. ArduinoFrontend/src/app/dashboard/dashboard.component.html
3. ArduinoFrontend/src/app/Libs/SaveOnline.ts
4. ArduinoFrontend/src/app/Libs/SaveOffline.ts
5. ArduinoFrontend/src/app/Libs/Workspace.ts
6. ArduinoFrontend/src/app/Libs/ConvertJSONFormat.ts
7. ArduinoFrontend/src/app/Libs/ImageToByteArray.ts
- Tested importing of circuit JSON files.
- Tested exporting of circuit JSON files.
- Tested all the above scenarios in both development & production environment.

Importexport

---

ArduinoFrontend/src/app/header/header.component.html
ArduinoFrontend/src/app/simulator/simulator.component.html

Fix the  dashboard header when user login.

header fix rewrite code

---

eda-frontend/package-lock.json
eda-frontend/package.json
eda-frontend/src/components/Project/CreateProject.js
eda-frontend/src/components/Project/ProjectTimeline.js
eda-frontend/src/components/Project/ReportComponent.js
eda-frontend/src/components/SchematicEditor/Header.js
eda-frontend/src/components/Shared/Navbar.js
eda-frontend/src/pages/ProjectPage.js
eda-frontend/src/redux/actions/actions.js
eda-frontend/src/redux/actions/projectActions.js
eda-frontend/src/redux/reducers/projectReducer.js
esim-cloud-backend/publishAPI/admin.py
esim-cloud-backend/publishAPI/models.py
esim-cloud-backend/publishAPI/serializers.py
esim-cloud-backend/publishAPI/views.py
esim-cloud-backend/saveAPI/models.py
esim-cloud-backend/workflowAPI/admin.py
esim-cloud-backend/workflowAPI/fixtures/initial_setup.json
esim-cloud-backend/workflowAPI/models.py
esim-cloud-backend/workflowAPI/utils.py
esim-cloud-backend/workflowAPI/views.py

This integrates a clean timeline into the workflow-versioning system.

Integrating Timeline in WorkflowAPI

---

ArduinoFrontend/package-lock.json
ArduinoFrontend/src/app/Libs/General.ts

This Pull request fixes Issue #291.
**Changes**:
Now each time the breadboard will be **dragged** a **function** will be called to rebuild `SameXNodes` & `SameYNodes` objects.

Breadboard issue fix #291

---

.github/workflows/reactTestBuild.yml
eda-frontend/src/components/SchematicEditor/Helper/ComponentDrag.js
eda-frontend/src/components/SchematicEditor/Helper/KeyboardShorcuts.js
eda-frontend/src/components/SchematicEditor/Helper/SvgParser.js
eda-frontend/src/components/SchematicEditor/Helper/ToolbarTools.js
eda-frontend/src/components/SchematicEditor/SchematicToolbar.js
eda-frontend/src/components/SchematicEditor/ToolbarExtension.js

Add following keybindings:
- Save: Ctrl + S
- Print: Ctrl + P
- Open Dialog: Ctrl + O
- Export as JSON: Ctrl + E ; Export as Image: Ctrl + Shift + E
- Rotate Component: Ctrl + R
- Delete Component: Del; Clear All: Shift + Del
- Undo: Ctrl + Z; Redo: Ctrl + Shift + Z
- Zoom In: Ctrl + +
- Zoom Out: Ctrl + -
-  Default Zoom: Ctrl + Y

Added new keybindings

---

Nginx/dev.conf.d/local.conf

Fix the issue described in #310

Bug fix for react auto reloading

---

ArduinoFrontend/src/app/Libs/General.ts

This PR fixes #324 
Changes done:
1. Modified the existing condition to return false in case of straight-line oriented nodes

Breadboard value transfer issue fix

---

eda-frontend/src/components/SchematicEditor/Helper/ComponentDrag.js
eda-frontend/src/components/SchematicEditor/Helper/KiCadFileUtils.js
eda-frontend/src/components/SchematicEditor/Helper/SvgParser.js
eda-frontend/src/components/SchematicEditor/Helper/ToolbarTools.js
eda-frontend/src/components/SchematicEditor/SchematicToolbar.js
eda-frontend/src/components/SchematicEditor/ToolbarExtension.js
eda-frontend/src/pages/SchematiEditor.js

What Works:
- Import features works for fairly complex schematics just bear in mind the issues.
Issues:
- Components that are not already present in the system cause unexpected behavior and may crash the page. It will be able to handle some cases.
- Connections (one end point of the wire is a wire) work fine. But nested connections(one end point of the wire is another connection or further) do not. Further testing required. 
- Path detection of a wire is not perfect expect some differences in appearance from kicad schematic.

Import KiCad schematic files(.sch files) into eSim

---

eda-frontend/src/components/SchematicEditor/Helper/ToolbarTools.js
eda-frontend/src/components/SchematicEditor/SimulationProperties.js

This adds a check where circuits are not simulated if they are incomplete or there is an error in generation of netlist or nodelist.

Enchancements in Simulation Screen

---

esim-cloud-backend/workflowAPI/fixtures/gallery_setup.json

- Deleted library dependency for gallery circuits, thus removing the need to find the corresponding eSim library.
- esim-cloud-backend/workflowAPI/fixtures/gallery_setup.json

HotFix To Load Gallery In Instances With Existing Data

---

eda-frontend/src/components/SchematicEditor/Helper/ToolbarTools.js
eda-frontend/src/components/SchematicEditor/SchematicToolbar.js
eda-frontend/src/components/SchematicEditor/SimulationProperties.js
eda-frontend/src/pages/Simulator.js
esim-cloud-backend/simulationAPI/helpers/ngspice_helper.py

Noise Analysis

---

eda-frontend/src/components/SchematicEditor/Header.js
eda-frontend/src/components/Shared/Navbar.js

Fixed issue of navbar after login at Schematic Editor

Aayush navbar

---

ArduinoFrontend/src/app/api.service.ts
ArduinoFrontend/src/app/dashboard/dashboard.component.ts
ArduinoFrontend/src/app/versioning-panel/create-variation-dialog/create-variation-dialog.component.html
ArduinoFrontend/src/app/versioning-panel/create-variation-dialog/create-variation-dialog.component.ts

Files changed:
ArduinoFrontend/src/app/api.service.ts
ArduinoFrontend/src/app/dashboard/dashboard.component.ts
ArduinoFrontend/src/app/create-variation-dialog/create-variation-dialog.component.ts
ArduinoFrontend/src/app/create-variation-dialog/create-variation-dialog.component.html

Fixed the issue of deleting circuits and validating variation names

---

ArduinoFrontend/src/app/api.service.ts
ArduinoFrontend/src/app/dashboard/dashboard.component.html
ArduinoFrontend/src/app/dashboard/dashboard.component.ts
ArduinoFrontend/src/app/simulator/simulator.component.ts
ArduinoFrontend/src/app/view-project/view-project.component.html
ArduinoFrontend/src/app/view-project/view-project.component.ts

Anonymous/Guest users can view the shared circuits of Arduino on Cloud using sharing URL
Now, shared URL contains latest branch and version of the shared circuit.
**Files changed**
ArduinoFrontend/src/app/dashboard/dashboard.component.ts
ArduinoFrontend/src/app/view-project/view-project.component.ts
ArduinoFrontend/src/app/view-project/view-project.component.html
ArduinoFrontend/src/app/simulator/simulator.component.ts
ArduinoFrontend/src/app/api.service.ts

Fixed the issue of guest users not able to view the shared Arduino circuits

---

eda-frontend/src/components/SchematicEditor/Header.js
eda-frontend/src/components/SchematicEditor/ToolbarExtension.js
eda-frontend/src/pages/SchematiEditor.js

-Solved the redirect issue for Home page through the navbar in the Schematic Editor by creating a dialog box and giving option to save the changes first.

Save changes before redirecting to Home

---

ArduinoFrontend/src/app/app-routing.module.ts
eda-frontend/src/components/SchematicEditor/Header.js
eda-frontend/src/components/SchematicEditor/SchematicToolbar.js

1. Modified Dashboard UI.
2. Add staff Functionality to Arduino Project.
3. Removing React Eslint Errors

Modified dashboard page

---

eda-frontend/src/components/LTI/LTI.js
esim-cloud-backend/simulationAPI/urls.py
esim-cloud-backend/simulationAPI/views.py

Fixed the bug appearing while creating an LTI and the test case drop down shows none.

Bug fix in LTI

---

ArduinoFrontend/src/app/code-editor/code-editor.component.html

Bugfix for Issues: #476  and #478

Arduino parallel execution bugfix

---

ArduinoFrontend/src/app/Libs/outputs/Motors.ts

Commit 3cecf22 : Bugfix for Issue #472 
Commit 54b4016 : Bugfix for Issue #474

Servo connection issues bugfix
